# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ed0c3df210bd8ac1fbed54ae14d7c66319b784afdeaf95ac9146bea1e48600c7de597b6c2b517003aa16a7c9d260a7bd9440276408c9a4c6a9c780c7b58d565

test:
  secret_key_base: 0ce6823df32f903f44e3d8d722dd0e48857271ba1635b0adbd242c758394340a12b14bf301858ef9ad7ad93bd12db94f9bcd7d2fc2a359096a0dd983dcf8b364

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
